# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Taiming Wang
# subtitle: lalala
email: taimingwang@ruc.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# twitter_username: username
github_username: TaimingWang
minimal_mistakes_skin: air #default is air, contrast, aqua
search: false
# repository: "NWO/taimingwang.github.io"
# logo: "/assets/images/logo.png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
url: "https://taimingwang.github.io"
# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-katex
  - jemoji
  - jekyll-include-cache

author:
  name: "Taiming Wang"
  avatar: "/assets/images/parrot.jpg"
  bio: "School of Economics, Renmin University of China."
  location: "Beijing, China"
  links:
    - label: "Homepage"
      icon: "fas fa-fw fa-link"
      url: "https://taimingwang.github.io/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/TaimingWang/"
    - label: "E-mail"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:taimingwang@ruc.edu.cn"

# footer:
  # links:
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://twitter.com/"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/TaimingWang/"



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      classes: wide
      show_date: flase
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
atom_feed:
  hide: true
  
 
# katex:
#   js_path: "{{ Gem::lib_path }}/assets/js"  # Path used to search for katex.min.js
#   rendering_options:
#     # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
#     throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
#     error_color: "#cc0000"                  # errorColor
